openapi: 3.0.3
info:
  version: 0.4.0
  title: 'DCSA OpenAPI specification for Electronic Bill of Lading'
  description: 'API specification issued by DCSA.org.<br>For explanation to specific values or objects please refer to the <a href="https://dcsa.org/wp-content/uploads/2020/12/20201208-DCSA-P1-DCSA-Information-Model-v3.0-FINAL.pdf">Information Model v3.0</a>'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: https://dcsa.org
    email: info@dcsa.org
paths:
  /shipping-instructions:
    post:
      tags:
       - Shipping Instructions
      summary: Post shipping instruction
      description: |
        Creates a new shipping instruction
      requestBody:
        description: Parameters used to create the shipping instruction
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstructionNoID'
      responses:
        '202':
          description: Shipping Instruction accepted
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstruction'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'
      callbacks:
        shipmentNotification:
          '{$request.body.callbackUrl}':
            post:
              parameters:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_NOTIFICATION_DOMAIN/1.0.0#/components/parameters/signatureHeaderParam'
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_NOTIFICATION_DOMAIN/1.0.0#/components/schemas/shipmentNotification'
              responses:
                '200':
                  description: 'Your server returns this code if it accepts the callback'          
    get:
      tags:
       - Shipping Instructions
      summary: Get shipping instruction
      description: 'Retrieves the shipping instruction &apos;metadata&apos; with the ID in the path.'
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/parameters/limitQueryParam'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/parameters/cursorQueryParam'
        - $ref: '#/components/parameters/carrierBookingReferenceQueryParam'
      responses:
        '200':
          description: Request successful        
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstructionHeader'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'            
  /shipping-instructions/{shippingInstructionID}:
    get:
      tags:
       - Shipping Instructions
      summary: Get shipping instruction
      description: Retrieves the shipping instruction with the ID in the path.
      parameters:
        - $ref: '#/components/parameters/shippingInstructionIDPathParam'
      responses:
        '200':
          description: Request successful        
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstruction'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'
    put:
      tags:
       - Shipping Instructions
      summary: Put shipping instruction
      parameters:
        - $ref: '#/components/parameters/shippingInstructionIDPathParam'
      description: |
        Updates a shipping instruction
      requestBody:
        description: Parameters used to update the shipping instruction
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstructionNoDS'
      responses:
        '200':
          description: Shipping Instruction updated
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/shippingInstruction'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'            
  /transport-documents:
    get:
      tags:
       - Transport Documents
      summary: Get Transport Documents
      description: Retrieves all Transport Documents
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/parameters/limitQueryParam'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/parameters/cursorQueryParam'
        - $ref: '#/components/parameters/carrierBookingReferenceQueryParam'
      responses:
        '200':
          description: Request successful        
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/transportDocumentHeader'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'
  /transport-documents/{transportDocumentID}:
    get:
      tags:
       - Transport Documents
      summary: Get Transport Document
      description: Retrieves the transport document with the ID in the path.
      parameters:
        - $ref: '#/components/parameters/transportDocumentIDPathParam'
        - $ref: '#/components/parameters/displayChargesQueryParam'
      responses:
        '200':
          description: Request successful
          headers:
            X-Document-Signature:
              schema:
                type: string
              description: The Carrier signature of the Transport Document
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/transportDocument'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error'
  /transport-documents/{transportDocumentID}/approval:
    post:
      tags:
       - Transport Documents
      summary: Approve a Transport Document.
      description: |
        Approves a Transport Document.
      parameters:
        - $ref: '#/components/parameters/transportDocumentIDPathParam'
        - $ref: '#/components/parameters/documentSignatureQueryParam'
      responses:
        '200':
          description: The Transport Document
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_EBL_DOMAIN/1.0.0#/components/schemas/transportDocument'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/error' 

components:
  parameters:
  
    #############
    # Path params
    #############
    
    shippingInstructionIDPathParam:
      in: path
      name: shippingInstructionID
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shippingInstructionID'
      required: true
    transportDocumentIDPathParam:
      in: path
      name: transportDocumentID
      description: The transportDocumentID of the transportDocument
      required: true
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportDocumentID'
  
    ##############
    # Query params
    ##############
    
    carrierBookingReferenceQueryParam:
      in: query
      name: carrierBookingReference
      description: 'A set of unique characters provided by carrier to identify a booking.'
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierBookingReference'
    displayChargesQueryParam:
      in: query
      name: displayCharges
      description: 'If set to true the payload will contain a list of charges connected to the TransportDocument. If <i>displayCharges</i> is <b>omitted</b> or set to false - no charges will be included in the payload.'
      schema:
        type: boolean
        enum:
          - true
          - false
      required: false
    documentSignatureQueryParam:
      in: query
      name: documentSignature
      description: The signature of the Transport Document to approve
      schema:
        type: string
      required: true