# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA - Operational Vessel Schedules (OVS) Components
  description: |
    Common components for DCSA APIs. This domain is used by
    - Operational Vessel Schedules API (<a href="https://app.swaggerhub.com/apis/dcsaorg/DCSA_OVS">OVS</a>)
    - Track & Trace API (<a href="https://app.swaggerhub.com/apis/dcsaorg/DCSA_TNT">TNT</a>)
  version: '1.0.0'

components:
  schemas:
    timestamp:
      description: |
        A digital record of the time of occurrence of a particular event
      type: object
      allOf:
        - type: object
          properties:
            publisher:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DOCUMENTATION_DOMAIN/1.0.0#/components/schemas/partyNoID'
        - type: object
          properties:
            publisherRole:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/partyFunction'
                - description: The party function code of the publisher
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            vesselPosition:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/LOCATION_DOMAIN/1.0.0#/components/schemas/geoLocation'
                - required:
                  - latitude
                  - longitude
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationCode'
        - type: object
          properties:
            facilityCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityCode'
        - type: object
          properties:
            facilityCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityCodeListProvider'
        - type: object
          properties:
            facilityTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityTypeCode'
        - type: object
          properties:
            GLNNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/GLNNumber'
        - type: object
          properties:
            eventClassifierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.0#/components/schemas/eventClassifierCode'
        - type: object
          properties:
            operationsEventTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.0#/components/schemas/operationsEventTypeCode'
        - type: object
          properties:
            modeOfTransportCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/modeOfTransportCode'
        - type: object
          properties:
            eventDateTime:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.0#/components/schemas/eventDateTime'
      required:
        - publisher
        - publisherRole
        - vesselIMONumber
        - vesselPosition
        - UNLocationCode
        - facilityCode
        - facilityCodeListProvider
        - facilityTypeCode
        - eventClassifierCode
        - operationsEventTypeCode
        - modeOfTransportCode
        - eventDateTime
    schedule:
      description: A timed plan that defines at what date or time terminals will be serviced by an ocean vessel. Schedules can have single (on a specific day/time only) or repetitive occurrences (e.g. every weekday at x hours).
      type: object
      allOf:
        - type: object
          properties: 
            scheduleID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/scheduleID'
        - type: object
          properties:
            vesselOperatorCarrierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCode'
        - type: object
          properties:
            vesselOperatorCarrierCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCodeListProvider'
        - type: object
          properties:
            vesselPartnerCarrierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselPartnerCarrierCode'
        - type: object
          properties:
            vesselPartnerCarrierCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselPartnerCarrierCodeListProvider'
        - type: object
          properties:
            startDate:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/startDate'
        - type: object
          properties:
            dateRange:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/dateRange'
      required:
        - scheduleID
        - vesselOperatorCarrierCode
        - vesselOperatorCarrierCodeListProvider
    

    transportCallBody:
      description:  A list of all the locations involved in a transport journey.
      type: object
      allOf:
        - type: object
          properties:
            scheduleID:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/scheduleID'
        - type: object
          properties:
            carrierServiceCode:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
                -  $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierServiceCode'
        - type: object
          properties:
            vessel: 
              $ref: '#/components/schemas/vessel'
        - type: object
          properties:
            vesselIMONumber:
              deprecated: true
              description: "Depricated in Transport Calls, please see vessel"
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            vesselName:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselName'
        - type: object
          properties:
            carrierVoyageNumber:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierVoyageNumber'
        - type: object
          properties:
            UNLocationCode:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationCode'
        - type: object
          properties:
            UNLocationName:
              deprecated: true
              description: "Depricated in Transport Calls"
              allOf:
              - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationName'
        - type: object
          properties:
            transportCallSequenceNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallSequenceNumber'
        - type: object
          properties:
            facilityTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityTypeCode'
        - type: object
          properties:
            facilityCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityCode'
        - type: object
          properties:
            otherFacility:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/otherFacility'
        - type: object
          properties:
            locationId:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/locationID'
      required:
        - facilityTypeCode
        - facilityCode
        
    transportCall:
      description: ""
      type: object
      allOf:
        - type: object
          properties:
            transportCallID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallID'
        - $ref: '#/components/schemas/transportCallBody'
        
    vessel:
      description: ""
      type: object
      allOf:
        - type: object
          properties: 
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties: 
            vesselName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselName'
        - type: object
          properties: 
            vesselFlag:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselFlag'
        - type: object
          properties: 
            vesselCallSignNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselCallSignNumber'
        - type: object
          properties:
            vesselOperatorCarrierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCode'
        - type: object
          properties:
            vesselOperatorCarrierCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCodeListProvider'