# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA - Operational Vessel Schedules (OVS) Components
  description: |
    Common components for DCSA APIs. This domain is used by
    - Operational Vessel Schedules API (<a href="https://app.swaggerhub.com/apis/dcsaorg/DCSA_OVS">OVS</a>)
    - Track & Trace API (<a href="https://app.swaggerhub.com/apis/dcsaorg/DCSA_TNT">TNT</a>)
  version: '1.0.0'

components:
  schemas:
    timestamp:
      description: |
        A digital record of the time of occurrence of a particular event
      type: object
      allOf:
        - type: object
          properties:
            publisher:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DOCUMENTATION_DOMAIN/1.0.1#/components/schemas/partyNoID'
        - type: object
          properties:
            publisherRole:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/partyFunction'
        # Extend the value of partyFunctions for publisherRole
        - type: object
          properties:
            publisherRole:
              description: |
                The party function code of the publisher:
                - CA (Carrier)
                - AG (Carrier local agent)
                - VSL (Experimental: Vessel)
                - ATH (Experimental: Port Authorities)
                - PLT (Experimental: Port Pilot)
                - TR (Terminal)
              enum:
                - CA
                - AG
                - VSL
                - ATH
                - PLT
                - TR
              example: TR
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/UNLocationCode'
        - type: object
          properties:
            facilitySMDGCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/facilityCode'
        # facilitySMDGCode repeated in order to "modify" the description of facilitySMDGCode to also include the word "SMDG"...
        - type: object
          properties:
            facilitySMDGCode:
              allOf:
                - description: The SMDG code used for identifying the specific facility. This code does not include the UN Location Code.
        # - type: object
        #   properties:
        #     facilityCodeListProvider:
        #       $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/facilityCodeListProvider'
        - type: object
          properties:
            facilityTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/facilityTypeCodeOPR'
        - type: object
          properties:
            eventClassifierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.1#/components/schemas/eventClassifierCode'
        - type: object
          properties:
            operationsEventTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.1#/components/schemas/operationsEventTypeCode'
        - type: object
          properties:
            eventLocation:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/LOCATION_DOMAIN/1.0.1#/components/schemas/location'
        - type: object
          properties:
            vesselPosition:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/LOCATION_DOMAIN/1.0.1#/components/schemas/geoLocation'
                - required:
                  - latitude
                  - longitude
        - type: object
          properties:
            modeOfTransport:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/modeOfTransport'
        - type: object
          properties:
            portCallServiceTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.1#/components/schemas/portCallServiceTypeCode'
        - type: object
          properties:
            eventDateTime:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.0.1#/components/schemas/eventDateTime'
      required:
        - publisher
        - publisherRole
        - vesselIMONumber
        - UNLocationCode
        - facilityCode
        - facilityCodeListProvider
        - facilityTypeCode
        - eventClassifierCode
        - operationsEventTypeCode
        - eventDateTime