# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA - Operational Vessel Schedules (OVS) Components
  description: |
    Common components for DCSA APIs. This domain is used by
    - Operational Vessel Schedules API (<a href="https://app.swaggerhub.com/apis/dcsaorg/DCSA_OVS">OVS</a>)
  version: 1.0.3

components:
  schemas:
    timestamp:
      description: |
        A digital record of the time of occurrence of an Operations event
      type: object
      allOf:
        - type: object
          properties:
            publisher:
              # Refer to new Party object where CodeListName is included
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DOCUMENTATION_DOMAIN/1.0.4#/components/schemas/partyNoID'
        - type: object
          properties:
            publisherRole:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/publisherRole'
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/UNLocationCode'
        - type: object
          properties:
            facilitySMDGCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/facilityCode'
        # facilitySMDGCode repeated in order to "modify" the description of facilitySMDGCode to also include the word "SMDG"...
        - type: object
          properties:
            facilitySMDGCode:
              allOf:
                - description: |
                    The SMDG code used for identifying the specific facility. This code does not include the UN Location Code.
                    
                    <b>NB:</b> facilitySMDGCode is deprecated - facilityCode together with facilityCodeListProvider in the eventLocation object should be used instead.
                - deprecated: true
        # - type: object
        #   properties:
        #     facilityCodeListProvider:
        #       $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/facilityCodeListProvider'
        - type: object
          properties:
            facilityTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/facilityTypeCodeOPR'
        - type: object
          properties:
            eventClassifierCode:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/eventClassifierCode'
        - type: object
          properties:
            eventClassifierCode:
              type: string
              description: |
                Code for the event classifier.
                - PLN (Planned)
                - ACT (Actual)
                - REQ (Requested)
                - EST (Estimated)
              enum:
                - PLN
                - ACT
                - REQ
                - EST
              example: ACT
        - type: object
          properties:
            operationsEventTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/operationsEventTypeCode'
        - type: object
          properties:
            eventLocation:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/LOCATION_DOMAIN/1.0.3#/components/schemas/location'
        - type: object
          properties:
            vesselPosition:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/LOCATION_DOMAIN/1.0.3#/components/schemas/geoLocation'
                - required:
                  - latitude
                  - longitude
        - type: object
          properties:
            modeOfTransport:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/modeOfTransport'
        - type: object
          properties:
            portCallServiceTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/portCallServiceTypeCode'
        - type: object
          properties:
            portCallPhaseTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/portCallPhaseTypeCode'
        - type: object
          properties:
            eventDateTime:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/eventDateTime'
        - type: object
          properties:
            carrierVoyageNumber:
              allOf:
                - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/carrierVoyageNumber'
                - deprecated: true
                - description: |
                    The vessel operator-specific identifier of the Voyage.
                    
                    <b>Deprecated:</b> Use export- and/or importVoyageNumber instead
        - type: object
          properties:
            exportVoyageNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/exportVoyageNumber'
        - type: object
          properties:
            importVoyageNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/importVoyageNumber'
        - type: object
          properties:
            carrierServiceCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/carrierServiceCode'
        - type: object
          properties:
            transportCallSequenceNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/transportCallSequenceNumber'
        - type: object
          properties:
            remark:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/EVENT_DOMAIN/1.1.1#/components/schemas/remark'
        - type: object
          properties:
            delayReasonCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.3#/components/schemas/delayReasonCode'
      required:
        - publisher
        - publisherRole
        - vesselIMONumber
        - UNLocationCode
        - facilityCode
        - facilityCodeListProvider
        - eventClassifierCode
        - operationsEventTypeCode
        - eventDateTime
        - carrierVoyageNumber
        - carrierServiceCode