# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA - Operational Vessel Schedules (OVS) Components
  description: Common components for DCSA APIs
  version: '1.0.0'

components:
  schemas:
    ######################################
    # Schedule Related objects
    ######################################
    
    scheduleSubscriptionBody:
      description: The object used by the POST event-subscriptions endpoint
      type: object
      allOf:
        - $ref: '#/components/schemas/transportCallSubscriptionBody'
        - type: object
          properties: 
            callbackUrl:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/callbackUrl'
        - type: object
          properties:
            dateRange:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/dateRange'
        - type: object
          properties:
            startDate:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/startDate'
        - type: object
          properties:
            carrierServiceCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierServiceCode'
      required:
        - callbackUrl
    
    scheduleSubscription:
      allOf:
        - $ref: '#/components/schemas/subscriptionID'
        - $ref: '#/components/schemas/scheduleSubscriptionBody'
        
    schedule:
      description: A timed plan that defines at what date or time terminals will be serviced by an ocean vessel. Schedules can have single (on a specific day/time only) or repetitive occurrences (e.g. every weekday at x hours).
      type: object
      allOf:
        - type: object
          properties: 
            scheduleID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/scheduleID'
        - type: object
          properties:
            vesselOperatorCarrierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCode'
        - type: object
          properties:
            vesselOperatorCarrierCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselOperatorCarrierCodeListProvider'
        - type: object
          properties:
            vesselPartnerCarrierCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselPartnerCarrierCode'
        - type: object
          properties:
            vesselPartnerCarrierCodeListProvider:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselPartnerCarrierCodeListProvider'
        - type: object
          properties:
            startDate:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/startDate'
        - type: object
          properties:
            dateRange:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/dateRange'
      required:
        - scheduleID
        - vesselOperatorCarrierCode
        - vesselOperatorCarrierCodeListProvider
    
    ######################################
    # Transport Call related objects
    ######################################
    
    
    transportCallSubscriptionBody:
      description: The object used by the POST transport-calls-subscriptions endpoint
      type: object
      allOf:
        - type: object
          properties:
            callbackUrl:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/callbackUrl'
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties:
             carrierVoyageNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierVoyageNumber'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationCode'
      required:
        - callbackUrl
    transportCallSubscription:
      allOf:
        - $ref: '#/components/schemas/subscriptionID'
        - $ref: '#/components/schemas/transportCallSubscriptionBody'
    
    transportCallBody:
      description:  A list of all the locations involved in a transport journey.
      type: object
      allOf:
        - type: object
          properties:
            scheduleID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/scheduleID'
        - type: object
          properties:
            carrierServiceCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierServiceCode'
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            vesselName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselName'
        - type: object
          properties:
            carrierVoyageNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierVoyageNumber'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationCode'
        - type: object
          properties:
            UNLocationName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationName'
        - type: object
          properties:
            transportCallNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallNumber'
        - type: object
          properties:
            facilityTypeCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityTypeCode'
        - type: object
          properties:
            facilityCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/facilityCode'
        - type: object
          properties:
            otherFacility:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/otherFacility'
      required:
        - scheduleID
        - carrierVoyageNumber
        - UNLocationCode
        - facilityTypeCode
        - facilityCode
        
    transportCall:
      description: ""
      type: object
      allOf:
        - type: object
          properties:
            transportCallID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallID'
        - $ref: '#/components/schemas/transportCallBody'
        
    
    ######################################
    # Transport Event Related Objects
    ######################################

    transportNotification:
      description:  A list of all the transport-events involved in a portCall.
      type: object
      allOf:
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_NOTIFICATION_DOMAIN/1.0.0#/components/schemas/transportNotification'
          
      required:
        - transportCallID
        - timestampID
        - eventClassiefierCode
        - transportEventTypeCode
        - locationType
        - locationID
        - eventDateTime

############################
#  Objects to be verified  #
############################
  
    subscriptionID:
      type: object
      properties:
        subscriptionID:
          $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/subscriptionID'
        


    transportCallID:
      type: object
      nullable: false
      properties:
        transportCallID:
          $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallID'
    
#########################
#String variables below #
#########################    
 

  headers:
    signatureHeader:
      schema:
        type: object
        properties:
          keyId:
            type: string
            format: uuid
            example: 123e4567-e89b-12d3-a456-426614174000
          created:
            type: integer
            example: 1591960384 
          headers:
            type: string
            example: "(request-target) (created) date host"
          signature:
            type: string
            example: aGkgZnJvbSBkZW5tYXJr
