# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA Event Components
  description: Common components for DCSA Events
  version: '1.0.0'

components:
  parameters:

    ####################
    ## Header parameters
    ####################

    signatureHeaderParam:
      in: header
      name: Signature
      required: true
      description: 'The signature certifying the request originates from the carrier.'
      explode: true
      schema:
        properties:
          keyId:
            type: string
            format: uuid
            example: 123e4567-e89b-12d3-a456-426614174000
          created:
            type: integer
            example: 1591960384 
          headers:
            type: string
            example: '(request-target) (created) date host'
          signature:
            type: string
            example: aGkgZnJvbSBkZW5tYXJr

  ####################
  # Common data models
  ####################
  
  schemas:
  
    ###################
    # Base Event object
    ###################

    events:
      type: array
      description: 'List of events for shipment journey.'
      items:
        $ref: '#/components/schemas/event'

    event:
      oneOf:
        - $ref: '#/components/schemas/shipmentEvent'
        - $ref: '#/components/schemas/equipmentEvent'
        - $ref: '#/components/schemas/transportEvent'
      discriminator:
        propertyName: eventType

    baseEvent:
      type: object
      description: 'The Event entity is described as a generalization of all the specific event categories. An event always takes place in relation to a shipment and can additionally be linked to a transport or an equipment'
      allOf:
        - type: object
          properties:
            eventID:
              $ref: '#/components/schemas/eventID'
        - type: object
          properties:
            eventType:
              $ref: '#/components/schemas/eventType'
        - type: object
          properties:
            eventCreatedDateTime:
              $ref: '#/components/schemas/eventCreatedDateTime'
        - type: object
          properties:
            eventSubtype:
              $ref: '#/components/schemas/eventSubtype'
        - type: object
          properties:
            eventClassifierCode:
              $ref: '#/components/schemas/eventClassifierCode'
        - type: object
          properties:
            eventDateTime:
              $ref: '#/components/schemas/eventDateTime'
      required:
        - eventID
        - eventType
        - eventCreatedDateTime
        - eventSubtype
        - eventClassifierCode
        - eventDateTime

    ##########################
    # Shipment Event object
    ##########################
    
    shipmentEvent:
      type: object
      description: 'The shipment event entity is a specialization of the event entity to support specification of data that only applies to a shipment event.'
      allOf:
        - $ref: '#/components/schemas/baseEvent'
        - type: object
          properties:
            eventType: #Overriding this property to have correct payload response examples
              example: SHIPMENT
              enum:
                - SHIPMENT
        - type: object
          properties:
            eventSubtype: #Overriding this property to have correct payload
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/documentStatus'
        - type: object
          properties:
            documentID:
              $ref: '#/components/schemas/documentID'
        - type: object
          properties:
            shipmentInformationTypeCode:
              $ref: '#/components/schemas/shipmentInformationType'
        - type: object
          properties:
            reason:
              $ref: '#/components/schemas/reason'
        
        #####################################
        # Deprecated ShipmentEvent attributes
        #####################################
        
        - type: object
          properties:
            eventDateTime:
              description: 'Value for eventDateTime must be the same value as eventCreatedDateTime'
        - type: object
          properties:
            eventClassifierCode:
              description: 'Code for the event classifier must be ACT (ACTUAL)'
              enum:
                - ACT
              example: ACT
        - type: object
          properties:
            eventTypeCode:
              $ref: '#/components/schemas/eventTypeCode'
        - type: object
          properties:
            eventTypeCode:
              description: |
                Unique identifier for Event Type Code. For shipment events this can be:
                - RECE (Received)
                - CONF (Confirmed)
                - ISSU (Issued)
                - APPR (Approved)
                - SUBM (Submitted)
                - SURR (Surrendered)
                - REJE (Rejected)
                - PENA (Pending approval)
                
                Deprecated - use eventSubtype instead
              deprecated: true
              example: RECE
              enum:
                - RECE
                - CONF
                - ISSU
                - APPR
                - SUBM
                - SURR
                - REJE
                - PENA
        - type: object
          properties:
            shipmentID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shipmentID'
        - type: object
          properties:
            shipmentID:
              description: |
                ID uniquely identifying a shipment.
                
                Deprecated - this is replaced by documentID which can contain different values depending on the value of the ShipmentInformationTypeCode field
              deprecated: true
      required:
        - documentID
        - shipmentInformationTypeCode

    ###############################
    # Transport Event object
    ###############################
    
    transportEvent:
      type: object
      description: 'The transport event entity is a specialization of the event entity to support specification of data that only applies to a transport event.'
      allOf:
        - $ref: '#/components/schemas/baseEvent'
        - type: object
          properties:
            eventType: #Overriding this property to have correct payload response examples
              example: TRANSPORT
              enum:
                - TRANSPORT
        - type: object
          properties:
            eventClassifierCode:
              $ref: '#/components/schemas/eventClassifierCode'
        - type: object
          properties:
            eventClassifierCode:
              description: |
                Code for the event classifier can be:
                - PLN (Planned)
                - ACT (Actual)
                - REQ (Requested)
                - EST (Estimated)
                <!-- - OPL (Operations planned) <font color="red"><- OBS - breaking change</font> -->
              enum:
                - ACT
                - EST
                - PLN
                - REQ
                # - OPL
              example: ACT
        - type: object
          properties:
            eventSubtype:
              type: string
              example: ARRI
              enum: 
                - ARRI
                - DEPA
              maxLength: 4
              description: |
                Unique identifier for EventSubtype, for transport events this is either:
                - ARRI (Arrival)
                - DEPA (Departure)
        - type: object
          properties:
            eventDateTime:
              $ref: '#/components/schemas/eventDateTime'
        - type: object
          properties:
            delayReasonCode:
              $ref: '#/components/schemas/delayReasonCode'
        - type: object
          properties:
            vesselScheduleChangeRemark:
              $ref: '#/components/schemas/vesselScheduleChangeRemark'
        - type: object
          properties:
            transportCallID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallID'
        - type: object
          properties:
            locationType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportLocationType'
        - type: object
          properties:
            locationID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/locationID'
        
        ######################################
        # Deprecated TransportEvent attributes
        ######################################
        
        - type: object
          properties:
            eventTypeCode:
              $ref: '#/components/schemas/eventTypeCode'
        - type: object
          properties:
            eventTypeCode:
              description: |
                Unique identifier for Event Type Code, for transport events this is either:
                - ARRI (Arrival)
                - DEPA (Departure)
                
                Deprecated - use eventSubType instead
              deprecated: true
              enum:
                - ARRI
                - DEPA
      required:
        - eventDateTime
        - eventClassifierCode
        - transportCallID

    ########################
    # Equipment Event object
    ########################
    
    equipmentEvent:
      type: object
      description: 'The equipment event entity is a specialization of the event entity to support specification of data that only applies to an equipment event.'
      allOf:
        - $ref: '#/components/schemas/baseEvent'
        - type: object
          properties:
            eventType: #Overriding this property to have correct payload response examples
              example: EQUIPMENT
              enum:
                - EQUIPMENT
        - type: object
          properties:
            eventDateTime:
              $ref: '#/components/schemas/eventDateTime'
        - type: object
          properties:
            eventSubtype:
              type: string
              example: LOAD
              enum: 
                - LOAD
                - DISC
                - GTIN
                - GTOT
                - STUF
                - STRP
              maxLength: 4
              description: | 
                Unique identifier for EventSubtype. For equipment events this can be:
                - LOAD (Load)
                - DISC (Discharge)
                - GTIN (Gate in)
                - GTOT (Gate out)
                - STUF (Stuffing)
                - STRP (Stripping)
        - type: object
          properties:
            eventClassifierCode:
              description: |
                Code for the event classifier can be:
                - PLN (Planned)
                - ACT (Actual)
              enum:
                - ACT
                - PLN
              example: ACT
        - type: object
          properties:
            equipmentReference:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/equipmentReference'
        - type: object
          properties:
            emptyIndicatorCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/emptyIndicatorCode'
        - type: object
          properties:
            transportCallID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportCallID'
        
        ######################################
        # Deprecated EquipmentEvent attributes
        ######################################
        
        - type: object
          properties:
            eventTypeCode:
              $ref: '#/components/schemas/eventTypeCode'
        - type: object
          properties:
            eventTypeCode:
              description: |
                Unique identifier for Event Type Code, for transport events this is either:
                - LOAD (Load)
                - DISC (Discharge)
                - GTIN (Gate in)
                - GTOT (Gate out)
                - STUF (Stuffing)
                - STRP (Stripping)
                
                Deprecated - use eventSubType instead
              deprecated: true
              enum: 
                - LOAD
                - DISC
                - GTIN
                - GTOT
                - STUF
                - STRP
      required:
        - emptyIndicatorCode
        - equipmentReference
        - transportCallID


    ##########################
    # Simple types
    ##########################
    
    callbackUrl:
      type: string
      format: uri
      description: 'The endPoint where a Carrier would send back events to the client'
      example: https://myserver.com/send/callback/here
    delayReasonCode:
      description: Reason code for the delay. The SMDG-Delay-Reason-Codes are used for this attribute. The code list can be found at http://www.smdg.org/smdg-code-lists/
      type: string
      maxLength: 3
      example: WEA
    documentID:
      type: string
      description: 'The id of the object defined by the Shipment Information Type. In some cases this is a UUID in other cases this is a string.'
    eventClassifierCode:
      type: string
      description: 'Code for the event classifier. Values can vary depending on eventType'
      #   - PLN (Planned)
      #   - ACT (Actual)
      #   - REQ (Requested)
      #   - EST (Estimated)
      # enum:
      #   - PLN
      #   - ACT
      #   - REQ
      #   - EST
      # example: EST
    eventID:
      type: string
      format: uuid
      description: 'The unique identifier for the event.'
      example: '84db923d-2a19-4eb0-beb5-446c1ec57d34'
    eventCreatedDateTime:
      type: string
      format: $date-time
      description: 'The timestamp of when the event was created'
      example: '2021-01-09T14:12:56+01:00'
    eventDateTime:
      type: string
      format: date-time
      example: '2019-11-12T07:41:00+08:30'
      description: The local date and time, where the event took place, in ISO 8601 format.
    eventType:
      type: string
      description: 'The Event Type of the object - to be used as a discriminator.'
      enum:
        - EQUIPMENT
        - SHIPMENT
        - TRANSPORT
    eventTypeCode:
      type: string
      example: ARRI
      maxLength: 4
      description: Deprecated - Unique identifier for Event Type Code. This code has different ENUM values depending on the type of event
      deprecated: true
    eventSubtype:
      type: string
      maxLength: 4
      description: 'The subType of the event. Values can vary depending on eventType'
    eventTypeList:
      description: 'A list of event types. Default is all events.'
      example: [EQUIPMENT,SHIPMENT,TRANSPORT]
      default: [EQUIPMENT,SHIPMENT,TRANSPORT]
      type: array
      items:
        $ref: '#/components/schemas/eventType'
    reason:
      type: string
      description: 'Reason field in a Shipment event. This field can be used to explain why a specific event has been sent.'
      example: 'The following attributes are missing...'
    shipmentInformationType:
      type: string
      maxLength: 3
      description: |
        The code to identify the type of information documentID points to. Can be one of the following values:
        - BOK (Booking)
        - SHI (Shipping Instruction)
        - VGM (Verified Gross Mass)
        - SRM (Shipment Release Message)
        - TRD (Transport Document)
        - ARN (Arrival Notice)
      example: SHI
      enum:
        - BOK
        - SHI
        - VGM
        - SRM
        - TRD
        - ARN
    signature:
      type: object
      properties:
        keyId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        created:
          type: integer
          example: 1591960384 
        headers:
          type: string
          example: '(request-target) (created) date host'
        signature:
          type: string
          example: aGkgZnJvbSBkZW5tYXJr
    subscriptionID:
      type: string
      format: uuid
      example: 123e4567-e89b-12d3-a456-426614174000
      description: 'The carrier issues a unique ID to the shipper or consignee for that subscription'
    vesselScheduleChangeRemark:
      description: 'Free text information provided by the vessel operator regarding the reasons for the change in schedule and/or plans to mitigate schedule slippage.'
      type: string
      example: Bad weather
      maxLength: 250
