openapi: 3.0.3
info:
  version: 1.0.0
  title: DCSA OpenAPI specification for Commercial Schedules
  description: |
    API specification issued by DCSA.org.
    
    For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/cs/v1#v100). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.
paths: {}