openapi: 3.0.3
info:
  version: 1.0.0
  title: DCSA OpenAPI specification for Commercial Schedules
  description: |
    API specification issued by DCSA.org.
    
    For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/cs/v1#v100). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: https://dcsa.org
    email: info@dcsa.org
paths:
  /v1/point-to-point-schedules:
    get:
      summary: Get Point-Point schedules
      description: |
        Retrieves the Point-Point schedules
      parameters:
        - $ref: '#/components/parameters/placeOfReceiptQueryParam'
        - $ref: '#/components/parameters/portOfLoadQueryParam'
        - $ref: '#/components/parameters/placeOfDeliveryQueryParam'
        - $ref: '#/components/parameters/portOfDischargeQueryParam'
        - $ref: '#/components/parameters/departureStartDateTimeQueryParam'
        - $ref: '#/components/parameters/departureEndDateTimeQueryParam'
        - $ref: '#/components/parameters/arrivalStartDateTimeQueryParam'
        - $ref: '#/components/parameters/arrivalEndDateTimeQueryParam'
        - $ref: '#/components/parameters/routingTypeCodeQueryParam'
        - $ref: '#/components/parameters/vesselFlagQueryParam'

        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/parameters/limit'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/parameters/cursor'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/parameters/sort'
        - $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/parameters/Api-Version-Major'
      responses:
        '200':
          description: Request successful
          headers:
            API-Version:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/API-Version'
            Current-Page:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/Current-Page'
            Next-Page:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/Next-Page'
            Prev-Page:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/Prev-Page'
            Last-Page:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/Last-Page'
            First-Page:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/First-Page'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pointToPoint'
        default:
          description: Unexpected error
          headers:
            API-Version:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/headers/API-Version'
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/ERROR_DOMAIN/1.1.0#/components/schemas/error'
components:
  schemas:
    dateTime:
      type: string
      format: date-time
      example: '2021-01-09T14:12:56+01:00'      
    pointToPoint:
      type: string
      maxLength: 3
      description: |
        The code to identify the type of information `documentID` points to. Can be one of the following values
        - CBR (Carrier Booking Request Reference)
        - BKG (Booking)

        More details can be found on <a href="https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/documenttypecodes.csv">GitHub</a>. Be aware that the list provided here is a subset of the possible values.
      example: CBR
      enum:
        - CBR
        - BKG

  parameters:
  
    ##############
    # Query params
    ##############
    
    placeOfReceiptQueryParam:
      in: query
      name: placeOfReceipt
      description: |
        `Place Of Receipt` defined as a UnLocationCode. Cannot be used in combination with `portOfLoad`
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/schemas/UNLocationCode'
      required: false
    portOfLoadQueryParam:
      in: query
      name: portOfLoad
      description: |
        `Port Of Load` defined as a UnLocationCode. Cannot be used in combination with `placeOfReceipt`
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/schemas/UNLocationCode'
      required: false
    placeOfDeliveryQueryParam:
      in: query
      name: placeOffDelivery
      description: |
        `Place Of fDelivery` defined as a UnLocationCode. Cannot be used in combination with `portOfDischarge`
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/schemas/UNLocationCode'
      required: false
    portOfDischargeQueryParam:
      in: query
      name: portOfDischarge
      description: |
        `Port Of Discharge` defined as a UnLocationCode. Cannot be used in combination with `placeOffDelivery`
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/schemas/UNLocationCode'
      required: false
    departureStartDateTimeQueryParam:
      in: query
      name: departureStartDateTime
      description: |
        Limit the result based on the departure start DateTime (earliest departure dateTme). This is a **conditional** field and `required` if `arrivalEndDateTime` is not specified.
        
        It is possible to use this query parameter in combination with the optional `departureEndDateTime`-queryParam. The maximum duration of the period allowed is 12 weeks (=3 months) which is also the default period used if `departureEndDateTime` is **not** defined.
        
        **NB:** A BadRequest is returned if the period exceeds 12 weeks or if this queryParameter is used in combination with either `arrivalStartDateTime` or `arrivalEndDateTime`
      required: false
      example: 2021-04-01T14:12:56+01:00
      schema:
        $ref: '#/components/schemas/dateTime'
    departureEndDateTimeQueryParam:
      in: query
      name: departureEndDateTime
      description: |
        Limit the result based on the departure end DateTime. It is not possible to combine this queryParameter with the `arrival`-queryParameters. It can **only** be used in combination with `departureStartDateTime` in which case it defines a period. If omitted the default value of this parameter in combination with `departureStartDateTime` is 12 weeks (=3 months)

        **NB:** A BadRequest is returned if the period exceeds 12 weeks or if this queryParameter is used in combination with either `arrivalStartDateTime` or `arrivalEndDateTime`
      required: false
      example: 2021-04-01T14:12:56+01:00
      schema:
        $ref: '#/components/schemas/dateTime'
    arrivalStartDateTimeQueryParam:
      in: query
      name: arrivalStartDateTime
      description: |
        Limit the result based on the arrival start DateTime. It is not possible to combine this queryParameter with the `departure`-queryParameters. It can **only** be used in combination with `arrivalEndDateTime` in which case it defines a period. If omitted the default value of this parameter in combination with `arrivalEndDateTime` is 12 weeks (=3 months)

        **NB:** A BadRequest is returned if the period exceeds 12 weeks or if this queryParameter is used in combination with either `departureStartDateTime` or `departureEndDateTime`
      required: false
      example: 2021-04-01T14:12:56+01:00
      schema:
        $ref: '#/components/schemas/dateTime'
    arrivalEndDateTimeQueryParam:
      in: query
      name: arrivalEndDateTime
      description: |
        Limit the result based on the arrival end DateTime (latest arrival dateTme). This is a **conditional** field and `required` if `departureStartDateTime` is not specified.
        
        It is possible to use this query parameter in combination with the optional `arrivalStartDateTime`-queryParam. The maximum duration of the period allowed is 12 weeks (=3 months) which is also the default period used if `arrivalStartDateTime` is **not** defined.
        
        **NB:** A BadRequest is returned if the period exceeds 12 weeks or if this queryParameter is used in combination with either `departureStartDateTime` or `departureEndDateTime`
      required: false
      example: 2021-04-01T14:12:56+01:00
      schema:
        $ref: '#/components/schemas/dateTime'
    vesselFlagQueryParam:
      in: query
      name: vesselFlag
      description: |
        The flag of the vessel. All Vessels in the results will belong to the specified flag
      schema:
        $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/2.0.0#/components/schemas/vesselFlag'
      required: false
    routingTypeCodeQueryParam:
      in: query
      name: routingTypeCode
      description: |
        Whether to use Direct-routing (`direct`) or Indirect-routing (`indirect`)
      schema:
        type: string
        enum:
          - direct
          - indirect
      required: false