# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################
info:
  title: DCSA - Location Components
  description: |
    Common components for DCSA Locations.
  version: 1.0.1

components:

  ####################
  # Common data models
  ####################
  schemas:
    location:
      type: object
      description: 'generally used to capture location-related data, also for locations without UN Location Codes.'
      allOf:
        # Remove locationID as this is not needed (1/6-2021) if needed later multiple location objects can be defined (one with and one without LocationNoID)
        # - type: object
        #   properties:
        #     locationID:
        #       $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/locationID'
        - type: object
          properties:
            locationName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/locationName'
        - type: object
          properties:
            latitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/latitude'
        - type: object
          properties:
            longitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/longitude'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/UNLocationCode'
        - type: object
          properties:
            address:
              description: 'Address related information'
              allOf:
                - $ref: '#/components/schemas/address'
    geoLocation:
      type: object
      description: 'on object used to capture latitude and longitude on a location'
      allOf:
        - type: object
          properties:
            latitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/latitude'
        - type: object
          properties:
            longitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/longitude'
    
    address:
      type: object
      description: 'An object for storing address related information'
      allOf:
        - type: object
          properties:
            name:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/addressName'
        - type: object
          properties:
            street:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/streetName'
        - type: object
          properties:
            streetNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/streetNumber'
        - type: object
          properties:
            floor:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/floor'
        - type: object
          properties:
            postCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/postCode'
        - type: object
          properties:
            city:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/cityName'
        - type: object
          properties:
            stateRegion:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/stateRegion'
        - type: object
          properties:
            country:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/country'